Add CI

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,6 +1,5 @@
-#!/bin/sh
-
-set -e
+#!/usr/bin/env bash
+set -e # halt script on error
 
 bundle exec jekyll build
-gem build jekyll-theme-cayman-blog.gemspec
+bundle exec htmlproofer ./_site
